AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 80

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false
